[TWITTER]
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAPw20wEAAAAA9DfHgDZkbWGgM1S%2BryaKJPtBupY%3Dcm6FbmxkB7VxxfhBbM7jBNOohFIyosuEHMZHYYOX8bOvi7G0dE"
API_KEY = "zI5TgX8NAHwLZlRHebqY5rvTr"
API_SECRET = "NNG3iJ9e13vTxxEOAdLC94oxSbA4zzYxxmEyQJbLMMACUAKJJO"
ACCESS_TOKEN = "1914972821891043328-dRlWQ3k75AnpRcbf4ShItZ1m0q2IVW"
ACCESS_TOKEN_SECRET = "u3OUqDI4cFRBXv6daOhHmqXJEtq50ocY6sXQzaCKfkEDe"